[package]
name = "calculator"
version = "0.2.0"
authors = ["rizalachp <rizal.ahmadp@gmail.com>"]
edition = "2021"

[dependencies]
rand        = { version = "0.8" }
itertools   = { version = "0.11" }
num-traits = "0.2.17"
